{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: "{{ .Chart.Name }}"
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/type: "{{ .Chart.Name }}"
{{ include "weather-service.labels" . | indent 4 }}
  annotations:
    helm.sh/hook: post-upgrade, post-install
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/type: "{{ .Chart.Name }}"
  {{- end }}