{{- $name := include "weather-service.name" . -}}
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}"
  labels:
    app.kubernetes.io/type: "{{ .Chart.Name }}"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/type: "{{ .Chart.Name }}"
