{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "weather-service.serviceAccountName" . }}
  labels:
    app: whatsapp
{{ include "weather-service.labels" . | indent 4 }}
{{- end }}
