imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

replicaCount: 1
image:
  repository: nginx
  tag: 1.20.0
  pullPolicy: Always

env:
  debugMode: true

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

podDisruptionBudget:
  enabled: true
  minAvailable: 50%
  maxUnavailable:

service:
  type: ClusterIP
  port: 80

livenessProbe:
  httpGet:
    path: /
    scheme: HTTP
    port: 80
  initialDelaySeconds: 7
  periodSeconds: 10
readinessProbe:
  httpGet:
    path: /
    scheme: HTTP
    port: 80
  initialDelaySeconds: 7
  periodSeconds: 10

serviceAccount:
  create: true
  name:

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
